# Generated by Django 4.2.6 on 2023-10-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DieselData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generator_id", models.CharField(max_length=50)),
                ("fuel_level", models.FloatField()),
                ("timestamp", models.DateTimeField()),
            ],
        ),
    ]
